services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PORT=5432'
    ports:
      - '5432:5432'
