services:

    traefik:
        container_name: traefik-hotelprauriu
        image: traefik:v3.3
        restart: unless-stopped
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.email=${DOMAIN_MAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "letsencrypt:/letsencrypt"
        networks:
            - hotelprauriu-network

    database:
        container_name: postgres-hotelprauriu
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - hotelprauriu-network

    hotelprauriu:
        image: ghcr.io/donatomartin/hotelprauriu/hotelprauriu-spring-app:latest
        restart: unless-stopped
        container_name: app-hotelprauriu            
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hotelprauriu.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
            - "traefik.http.routers.hotelprauriu.entrypoints=websecure"
            - "traefik.http.routers.hotelprauriu.tls.certresolver=myresolver"
            - "traefik.http.services.hotelprauriu.loadbalancer.server.port=${APP_PORT}"
        environment:
            JDBC_URL: ${JDBC_URL}
            DDL_AUTO: ${DDL_AUTO}
            SPRING_PROFILE: ${SPRING_PROFILE}
            GMAIL_ADDRESS: ${GMAIL_ADDRESS}
            GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
        depends_on:
            - database
        networks:
            - hotelprauriu-network

networks:
    hotelprauriu-network:
        driver: bridge
    
volumes:
    postgres-data:
    letsencrypt:

