services:

    traefik:
        container_name: traefik-hotelprauriu
        image: traefik:v3.3
        restart: unless-stopped
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.email=${DOMAIN_MAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "letsencrypt:/letsencrypt"
        networks:
            - hotelprauriu-network
        profiles:
            - prod

    database:
        container_name: postgres-hotelprauriu
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - hotelprauriu-network
        profiles:
            - prod

    hotelprauriu:
        image: ghcr.io/donatomartin/hotelprauriu-spring-app:latest
        restart: unless-stopped
        container_name: app-hotelprauriu            
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hotelprauriu.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
            - "traefik.http.routers.hotelprauriu.entrypoints=websecure"
            - "traefik.http.routers.hotelprauriu.tls.certresolver=myresolver"
            - "traefik.http.services.hotelprauriu.loadbalancer.server.port=${APP_PORT}"
        env_file: .env
        depends_on:
            - database
        networks:
            - hotelprauriu-network
        profiles:
            - prod

    dev-database:
        container_name: postgres-hotelprauriu
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - hotelprauriu-network
        ports:
            - "${POSTGRES_PORT}:5432"
        profiles:
            - dev

    dev-hotelprauriu:
        image: ghcr.io/donatomartin/hotelprauriu-spring-app:latest
        build:
            context: .
        restart: unless-stopped
        container_name: app-hotelprauriu            
        env_file: .env
        depends_on:
            - dev-database
        networks:
            - hotelprauriu-network
        profiles:
            - dev

networks:
    hotelprauriu-network:
        driver: bridge
    
volumes:
    postgres-data:
    letsencrypt:

