services:

    watchtower:
        container_name: watchtower-hotelprauriu
        image: containrrr/watchtower
        restart: unless-stopped
        command:
            - "--label-enable"
            - "--interval"
            - "30"
            - "--rolling-restart"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    traefik:
        container_name: traefik-hotelprauriu
        image: traefik:v3.3
        restart: unless-stopped
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.email=${DOMAIN_MAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "letsencrypt:/letsencrypt"
        networks:
            - hotelprauriu-network

    database:
        container_name: postgres-hotelprauriu
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - hotelprauriu-network

    hotelprauriu:
        image: ghcr.io/dononitram/hotelprauriu/app:latest
        restart: unless-stopped
        container_name: app-hotelprauriu            
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hotelprauriu.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.hotelprauriu.entrypoints=websecure"
            - "traefik.http.routers.hotelprauriu.tls.certresolver=myresolver"
            - "traefik.http.services.hotelprauriu.loadbalancer.server.port=8080"
            - "com.centurylinklabs.watchtower.enable=true"
        env_file: .env
        depends_on:
            - database
        networks:
            - hotelprauriu-network

networks:
    hotelprauriu-network:
        driver: bridge
    
volumes:
    postgres-data:
    letsencrypt:
