services:

    database:
        container_name: postgres-hotelprauriu
        image: postgres:latest
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    hotelprauriu:
        build: .
        container_name: app-hotelprauriu            
        env_file: .env
        depends_on:
            - database
        ports:
            - "80:8080"

volumes:
    postgres-data:
    letsencrypt:
