services:

  traefik:
    image: alpine  # dummy image
    command: ["/bin/true"]
    entrypoint: ["/bin/true"]
    ports: []
    volumes: [] 

  hotelprauriu:
    labels: []
    environment:
      - JDBC_URL=jdbc:postgresql://postgres-hotelprauriu:5432/postgres
    ports:
      - "8091:8080"
  
  database:
    ports:
      - "5432:5432"

