
name: Build and Deploy

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ${{ github.repository_owner }}/hotelprauriu/hotelprauriu-spring-app

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull and deploy containers

        env:
          SPRING_PROFILE: ${{ vars.SPRING_PROFILE }}

          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          JDBC_URL: ${{ secrets.JDBC_URL }}

          DDL_AUTO: ${{ vars.DDL_AUTO }}

          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

          DOMAIN: ${{ vars.DOMAIN }}
          DOMAIN_MAIL: ${{ vars.DOMAIN_MAIL }}

        run: |
          docker compose -f compose.yaml down
          docker compose -f compose.yaml up -d --pull always --remove-orphans
